# Generated by Django 4.1.4 on 2023-01-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_order_isdelivered_alter_order_ispaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder', null=True, upload_to=''),
        ),
    ]
